name: build all arch for sailfish

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    strategy:
      matrix:
        arch: ['armv7hl', 'aarch64', 'i486']

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Prepare
      run: mkdir output

    - name: Build (${{ matrix.arch }})
      uses: coderus/github-sfos-build@master
      with:
        arch: ${{ matrix.arch }}
        release: 4.5.0.16

    - name: Upload RPM (${{ matrix.arch }})
      uses: actions/upload-artifact@v4.4.3
      with:
        name: rpm-${{ matrix.arch }}
        path: RPMS

  release:
    runs-on: ubuntu-latest
    name: Release App
    needs: build
    if: contains(github.ref, 'v')
    steps:
    - name: Download RPM
      uses: actions/download-artifact@v4.1.8

    - name: Create release
      if: contains(github.ref, 'v')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" "${assets[@]}" 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

